name: Build Executables

on:
  push:
    branches:
      - master  # Adjust this branch name to your main branch name

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Rust
        uses: actions/checkout@v2
      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - name: Build for Linux
        run: cargo build --release

      - name: Archive Linux executable
        run: mv target/release/cpu_benchmark ./cpu_benchmark_linux
        if: ${{ success() }}

      - name: Install mingw
        run: sudo apt-get update && sudo apt-get install -y mingw-w64

      - name: Add Windows GNU target
        run: rustup target add x86_64-pc-windows-gnu

      - name: Build for Windows
        run: cargo build --target x86_64-pc-windows-gnu --release

      - name: Archive Windows executable
        run: mv target/x86_64-pc-windows-gnu/release/cpu_benchmark.exe ./cpu_benchmark_windows.exe
        if: ${{ success() }}

      - name: Add macOS target
        run: rustup target add x86_64-apple-darwin
        if: ${{ success() }}

      - name: Install macOS cross-compilation tools
        run: rustup target add x86_64-apple-darwin
        if: ${{ success() }}

      - name: Debug List target contents
        run: ls target/

      - name: Debug List available Rust targets
        run: rustup target list

      - name: Debug Check current target triple
        run: rustc --print target-list

      - name: Debug Check Cargo configuration
        run: cargo --version; rustc --version; rustup show

      - name: Install macOS dependency
        run: sudo apt-get install -y cmake g++-multilib

      - name: Install osxcross
        run: git clone --depth 1 https://github.com/tpoechtrager/osxcross /usr/local/osxcross && UNATTENDED=yes OSX_VERSION_MIN=10.7 /usr/local/osxcross/build.sh

      - name: Build for macOS
        env:
          PATH: ${{ env.OSXCROSS_PATH }}/target/bin:$PATH
          SDKROOT: ${{ env.OSXCROSS_PATH }}/target/SDK/MacOSX10.7.sdk
        run: cargo build --target x86_64-apple-darwin --release


      - name: Check target contents (macOS)
        run: ls target/x86_64-apple-darwin/release/

      - name: Archive macOS executable
        run: mv target/x86_64-apple-darwin/release/cpu_benchmark ./cpu_benchmark_macos
        if: ${{ success() }}

      - name: Save artifacts
        uses: actions/upload-artifact@v2
        with:
          name: executables
          path: |
            cpu_benchmark_linux
            cpu_benchmark_windows.exe
            cpu_benchmark_macos
