name: 'Release'

on:
  push:
    tags:
      - 'v*'

env:
  CARGO_INCREMENTAL: 0

jobs:
  build:
    name: Binary
    strategy:
      fail-fast: false
      matrix:
        job:
          - { target: x86_64-unknown-linux-musl, exe: amd64-linux, os: ubuntu-latest, features: default }
          - { target: aarch64-unknown-linux-musl, exe: aarch64-linux,  os: ubuntu-latest, features: default }
          - { target: armv7-unknown-linux-musleabi, exe: armv7-linux, os: ubuntu-latest, features: default }
          - { target: wasm32-wasi, exe: wasi.wasm, os: ubuntu-latest, features: "" }
          - { target: x86_64-apple-darwin, exe: macos, os: macos-latest, features: default }
          - { target: x86_64-pc-windows-msvc, exe: windows.exe, os: windows-2019, features: default }
    runs-on: ${{ matrix.job.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: 1.62.0
          override: true
          target: ${{ matrix.job.target }}
          components: rust-src
      - uses: actions-rs/cargo@v1
        with:
          use-cross: true
          args: --release --target=${{ matrix.job.target }} --locked
          command: build
      - name: Rename result
        run: |
          rm target/${{ matrix.job.target }}/release/cpu-benchmark.d
          cp target/${{ matrix.job.target }}/release/cpu-benchmark* cpu-benchmark-${{ matrix.job.exe }}

      - name: Archive production artifacts
        uses: actions/upload-artifact@v2
        with:
          name: arty
          path: cpu-benchmark-${{ matrix.job.exe }}

  #cargo-publish:
  #  runs-on: ubuntu-20.04
  #  needs: build
  #  steps:
  #    - uses: actions/checkout@v3

  #    - name: Cargo publish
  #      run: |
  #        git config --global user.email "runner@gha.local"
  #        git config --global user.name "Github Action"
  #        cargo publish --allow-dirty --token ${{ secrets.CRATES_IO_TOKEN }}
