name: Build Executables

on:
  push:
    branches:
      - master  # Adjust this branch name to your main branch name

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Rust
        uses: actions/checkout@v2
      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - name: Build for Linux
        run: cargo build --release

      - name: Archive Linux executable
        run: mv target/release/cpu_benchmark ./cpu_benchmark_linux
        if: ${{ success() }}

      - name: Install mingw
        run: sudo apt-get update && sudo apt-get install -y mingw-w64

      - name: Add Windows GNU target
        run: rustup target add x86_64-pc-windows-gnu

      - name: Build for Windows
        run: cargo build --target x86_64-pc-windows-gnu --release

      - name: Archive Windows executable
        run: mv target/x86_64-pc-windows-gnu/release/cpu_benchmark.exe ./cpu_benchmark_windows.exe
        if: ${{ success() }}

      - name: Debug List target contents
        run: ls target/

      - name: Debug List available Rust targets
        run: rustup target list

      - name: Debug Check current target triple
        run: rustc --print target-list

      - name: Debug Check Cargo configuration
        run: cargo --version; rustc --version; rustup show

      - name: Save artifacts
        uses: actions/upload-artifact@v2
        with:
          name: executables
          path: |
            cpu_benchmark_linux
            cpu_benchmark_windows.exe
            cpu_benchmark_macos
